export const ActionTypes = {
  FETCH_TASKS: "FETCH_TASKS:",
  SET_TASKS: "SET_TASKS",
  SELECTED_TASK: "SELECTED_TASK",
  SET_CODE: "SET_CODE",
  REMOVE_SELECTED_TASK: "REMOVE_SELECTED_TASK",
  SET_USER: "SET_USER",
  SET_USER_DETAIL: "SET_USER_DETAIL",
  PAGE_INCREMENT: "PAGE_INCREMENT",
  PAGE_DECREMENT: "PAGE_DECREMENT",
  SET_PAGE: "SET_Page",
  SET_TITLE: "SET_TITLE",
  SET_EASTEREGG: "SET_EASTEREGG",
};
